### ISSUE TITLE
read the json file , calculate the pixel coordinate

### ISSUE THREAD

**Issue by glacierwl** [SunDaDenny/PanoArchi_Tool#1]
hello, i have got the json file, but i don't know how to convert the json file to label_cor,that's to say,how can i calculate the corner pixel coordinate in the 2D image? thank you

**Comment by glacierwl** [comment]
I have solved it

**Comment by FocusK** [comment]
@glacierwl  Hi，Can you tell me how you solved it?

**Comment by glacierwl** [comment]
First, you should understand the meaning of json file. Then you should read the source code of this tool.
------------------
此情可待成追忆，只是当时已惘然。

---原始邮件---
发件人:&quot;FocusK&quot;<notifications@github.com&gt;
发送时间:2020年6月16日 星期二 下午10:26
收件人:&quot;SunDaDenny/PanoAnnotator&quot;<PanoAnnotator@noreply.github.com&gt;
抄送:&quot;glacierwl&quot;<1229755386@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;
主题:Re: [SunDaDenny/PanoAnnotator] read the json file , calculate the pixel coordinate (#1)



@glacierwlHi，Can&nbsp;you&nbsp;tell&nbsp;me&nbsp;how&nbsp;you&nbsp;solved&nbsp;it?

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;were&nbsp;mentioned.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by glacierwl** [comment]
Here is the reference method 




---原始邮件---
发件人:&quot;FocusK&quot;<notifications@github.com&gt;
发送时间:2020年6月16日 星期二 下午10:26
收件人:&quot;SunDaDenny/PanoAnnotator&quot;<PanoAnnotator@noreply.github.com&gt;
抄送:&quot;glacierwl&quot;<1229755386@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;
主题:Re: [SunDaDenny/PanoAnnotator] read the json file , calculate the pixel coordinate (#1)



@glacierwlHi，Can&nbsp;you&nbsp;tell&nbsp;me&nbsp;how&nbsp;you&nbsp;solved&nbsp;it?

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;were&nbsp;mentioned.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by glacierwl** [comment]
![abc](https://user-images.githubusercontent.com/49226023/109324597-d68aa900-788f-11eb-964c-b8d6e6deb3c7.jpg)
@FocusK
